spring.application.name=tenant-service
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/quinicastock
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update